sudo: false
language: c++

addons_shortcuts:
  addons_clang36: &clang36
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6']
      packages: [ 'clang-3.6' ]
  addons_gcc50: &gcc50
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-5' ]
  addons_gcc48: &gcc48
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-4.8' ]
      
matrix:
  include:
    - os: linux
      compiler: "clang++-3.6"
      env: COMPILER=clang++-3.6 BUILD_TYPE=Release
      addons: *clang36
    - os: linux
      compiler: "clang++-3.6"
      env: COMPILER=clang++-3.6 BUILD_TYPE=Debug
      addons: *clang36
    - os: linux
      compiler: "g++5.0"
      env: COMPILER=g++-5 BUILD_TYPE=Release
      addons: *gcc50
    - os: linux
      compiler: "g++5.0"
      env: COMPILER=g++-5 BUILD_TYPE=Debug
      addons: *gcc50
    - os: linux
      compiler: "g++4.8"
      env: COMPILER=g++-4.8 BUILD_TYPE=Debug
      addons: *gcc48




before_script:
  - curl http://www.lua.org/ftp/lua-5.3.2.tar.gz | tar xz
  - mv lua-5.3.2 lua
  - cd lua
  - make clean
  - make linux
  - cd ..
  
script:
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER="${COMPILER:-clang++}" && make && ./test_runner
