sudo: false
language: c++
compiler:
- clang
- gcc
addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise', 'llvm-toolchain-precise-3.8' ]
    packages:
      - gcc-5
      - g++-5
      - clang-3.8
      - libc6-dev
      - valgrind

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug VALGRIND='valgrind --leak-check=full --error-exitcode=1'

before_script:
  - curl http://www.lua.org/ftp/lua-5.3.2.tar.gz | tar xz
  - mv lua-5.3.2 lua
  - cd lua
  - make clean
  - make linux
  - cd ..
  
script:
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} && make && ${VALGRIND} ./test_runner