sudo: false
language: c++

addons_shortcuts:
  addons_clang39: &clang39
    apt:
      sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9']
      packages: [ 'clang-3.9' ]
  addons_gcc70: &gcc70
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-7' ]
      
matrix:
  include:
    - os: linux
      compiler: "clang++-3.9"
      env: COMPILER=clang++-3.9 BUILD_TYPE=Release
      addons: *clang39
    - os: linux
      compiler: "clang++-3.9"
      env: COMPILER=clang++-3.9 BUILD_TYPE=Debug
      addons: *clang39
    - os: linux
      compiler: "g++7"
      env: COMPILER=g++-7 BUILD_TYPE=Release
      addons: *gcc70
    - os: linux
      compiler: "g++7"
      env: COMPILER=g++-7 BUILD_TYPE=Debug
      addons: *gcc70


before_script:
  - curl http://www.lua.org/ftp/lua-5.3.2.tar.gz | tar xz
  - mv lua-5.3.2 lua
  - cd lua
  - make clean
  - make linux
  - cd ..
  
script:
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER="${COMPILER:-clang++}" && make && ./test_runner
