sudo: false
language: cpp
compiler: 
	- gcc
	- clang
	
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5.3" CC="gcc-5.3"; fi
  - sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.3.so /usr/lib/liblua.so
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5.3
    - g++-5.3
    - clang
    - valgrind
    - lua5.3
    - liblua5.3-dev
    
env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug VALGRIND='valgrind --leak-check=full --error-exitcode=1'

script:
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLUA_INCLUDE_DIR=/usr/include/lua5.3 && make && ${VALGRIND} ./test_runner