language: cpp

compiler: gcc

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo apt-get update -qq

install:
  - if [ "$CXX" = "g++" ]; then export PACKAGES_TO_INSTALL="g++-5.3"; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5.3"; fi
  - export PACKAGES_TO_INSTALL="${PACKAGES_TO_INSTALL} lua5.3 liblua5.3-dev"
  - export PACKAGES_TO_INSTALL="${PACKAGES_TO_INSTALL} valgrind"
  - sudo apt-get install -qq ${PACKAGES_TO_INSTALL}
  - sudo ln -s /usr/lib/x86_64-linux-gnu/liblua5.3.so /usr/lib/liblua.so

env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug VALGRIND='valgrind --leak-check=full --error-exitcode=1'

script:
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DLUA_INCLUDE_DIR=/usr/include/lua5.3 && make && ${VALGRIND} ./test_runner