sudo: false
language: c++

addons_shortcuts:
  #addons_clang38: &clang38
  #  apt:
  #    sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise', 'llvm-toolchain-precise-3.8' ]
  #    packages: [ 'clang-3.8' ]
  addons_clang34: &clang34
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'clang-3.4' ]
  addons_gcc50: &gcc50
    apt:
      sources: [ 'ubuntu-toolchain-r-test' ]
      packages: [ 'g++-5' ]
      
matrix:
  include:
    #- os: linux
    #  compiler: "clang3.8"
    #  env: COMPILER=clang++-3.8 BUILD_TYPE=Release
    #  addons: *clang38
    #- os: linux
    #  compiler: "clang3.8"
    #  env: COMPILER=clang++-3.8 BUILD_TYPE=Debug
    #  addons: *clang38
    - os: linux
      compiler: "clang3.4"
      env: COMPILER=clang++ BUILD_TYPE=Release
      addons: *clang34
    - os: linux
      compiler: "clang3.4"
      env: COMPILER=clang++ BUILD_TYPE=Debug
      addons: *clang34
    - os: linux
      compiler: "gcc5.0"
      env: COMPILER=g++-5 BUILD_TYPE=Release
      addons: *gcc50
    - os: linux
      compiler: "gcc5.0"
      env: COMPILER=g++-5 BUILD_TYPE=Debug
      addons: *gcc50




before_script:
  - curl http://www.lua.org/ftp/lua-5.3.2.tar.gz | tar xz
  - mv lua-5.3.2 lua
  - cd lua
  - make clean
  - make linux
  - cd ..
  
script:
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DCMAKE_CXX_COMPILER="${COMPILER:-clang++}" && make && ./test_runner
